### PR TITLE
support arrays of types using anyOf

### PR DESCRIPTION
**Pull request by theoephraim**
addresses #12

### CODE REVIEW

**Comment by theoephraim** [comment]
Ok - good to go! This seems to be rendering things correctly now in my [Redoc](https://github.com/Redocly/redoc) pages.

**Comment by philsturgeon** [comment]
Thank you so much! This is excellent, and you got it done really quickly and with tests. Let me know if I can buy you a coffee or [some trees](https://ecologi.com/philsturgeon).

**Comment by theoephraim** [comment]
No worries :)

Sure, I'd love some 🌲🌲🌲🌲 :D

I may have some more PRs as I get further into this project if I find anything else.

The project is pretty neat, I'm autogenerating an openAPI spec (and redoc site) from typescript using  https://github.com/YousefED/typescript-json-schema to pull out type info as well as comments, and then doing some conversion to OpenAPI using this module. Seems to be working pretty well!

**Comment by philsturgeon** [comment]
[50 trees](https://ecologi.com/philsturgeon?tree=5f17f9630a33e00017e7c2f9) and 1 tonne of CO2 have been removed via this pull request. 🤩

If you make your own account I'll chuck a few trees in when more PRs come.

**Pull request merged**
