### PR TITLE
convert.sync - sync version that does not dereference

### PR DESCRIPTION
**Pull request by theoephraim**
This introduces a new convert.sync method which is a synchronous version equivalent to calling with dereference = false.

In my use case the function being asynchronous introduced a whole chain of async function calls which added unnecessary complexity. This will help.

Thanks!!

### CODE REVIEW

**Comment by ap-simon** [comment]
Thanks for this one, works on my machine!

**Comment by JoshuaWise** [comment]
Any chance this will get merged in soon?

**Comment by theoephraim** [comment]
@philsturgeon - can we get this merged please? Thanks!

**Comment by philsturgeon** [comment]
My concern here is that it's only a partial implementation. Having a sync() without dereferencing is only useful for those who don't want dereferencing. For those who do, would it not be an unexpected outcome, and would it not block people who are trying to figure out why they've got $ref in there when the docs said it should be resolved? 

Either way, can you add documentation of which this method _is_ doing so that people know how it works?

**Pull request closed without merging**
